name: Rust

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:xenial
    steps:
    - uses: actions/checkout@v2
    - name: diagnostics
      run: apt-cache policy libstdc++6
    - name: update package list
      run: apt-get update
    - name: install dependencies
      run: apt-get -y install libzmq3-dev
    - name: abort
      run: exit 1
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Package
      run: cargo deb
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: target/debian/condure_*_amd64.deb
